name: Deploy Stream Chat Swagger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch OpenAPI JSON
        run: |
          curl -sL https://stream-openapi.s3.amazonaws.com/chat/openapi-latest.json -o openapi-latest.json

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output: chat/docs/rest
          spec-file: openapi-latest.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: chat/docs/rest
